name: mkv-projects
favicon: null
layout_spectrum: 0.09446640941314399
typography_spectrum: 0.09387679025530815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.125
  lightness: 0.9559591400902718
  saturation: 0.1333115806337446
  rhythmicContrast: 0.07171886437572539
purpose: []
