analytics: {}
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.125
  lightness: 0.955959
  rhythmicContrast: 0.318693
  saturation: 0.402027
cta: {}
layout_spectrum: 0.09446640941314399
name: mkv-projects
opengraph: {}
purpose: []
typography_spectrum: 0.09387679025530815
